name: GitHub Actions Week 14 
run-name: ${{ github.actor }} is testing checking for issues on week 14 lab 
on: [push] 
jobs:
  test-for-insecure-modules: 
    runs-on: ubuntu-latest 
    env:
      working-directory-insecure: ./insecure
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - run: (cd insecure && npm install)
    - run: (cd insecure && npm audit)
    - run: echo "Testing for insecure modules"

  detect-messed-up-JS:
    runs-on: ubuntu-latest
    steps:
    - name: Check if code cormat is correct
      uses: actions/checkout@v3
    - run: (cd mashup && npm install)
    - run: (cd mashup && npm run lint)
    - run: echo "Doing js quality check"

  run-unit-testing:
    runs-on: ubuntu-latest
    steps:
    - name: Tests code
      uses: actions/checkout@v3
    - run: (cd unittesting && npm install)
    - run: (cd unittesting && npm run test)
    - run: echo "Testing for issues"